### ISSUE TITLE
composer cant find 5.0.1 which comes from zip file in composer.json

### ISSUE THREAD

**Issue by frithjof** [pimcore/pimcore-cli#11]
After Filesystem migrate composer update throws

Problem 1
    - The requested package pimcore/core-version v5.0.1 exists as pimcore/core-version[4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 5.0.0-alpha.1, dev-master, v5.0.0, v5.0.0-RC] but these are rejected by your constraint.

**Comment by brusch** [comment]
Unfortunately we had a broken release file for 5.0.1 - fixed. 
Thanks!
